// Shared renderer utilities

        export const Utils = {
            formatAppName(packageName) {
                if (!packageName) return "Unknown";
                const parts = packageName.split('.');
                let name = parts[parts.length - 1];
                if ((name === 'android' || name === 'app') && parts.length > 1) name = parts[parts.length - 2];
                return name.charAt(0).toUpperCase() + name.slice(1);
            },
    
            formatBytes(bytes, decimals = 2) {
                if (!+bytes) return '0 Bytes';
                const k = 1024;
                const i = Math.floor(Math.log(bytes) / Math.log(k));
                return `${parseFloat((bytes / Math.pow(k, i)).toFixed(decimals < 0 ? 0 : decimals))} ${['Bytes', 'KB', 'MB', 'GB', 'TB'][i]}`;
            },
    
            transformAndroidData: (scanData) => {
                const transformedApps = scanData.allApps || [];
    
                // 1. 진짜 스파이앱 (VT 확진된 것만)
                const spyApps = transformedApps.filter(app =>
                    // app.reason && app.reason.includes('[VT 확진]')
                    false
                );
    
                // 2. 개인정보 유출 위협 (권한이 과도하거나 VT 결과가 애매한 의심 앱)
                const privacyThreats = transformedApps.filter(app =>
                    app.reason // && !app.reason.includes('[VT 확진]')
                );
    
                return {
                    deviceInfo: scanData.deviceInfo,
                    allApps: transformedApps,
                    apkFiles: scanData.apkFiles || [],
                    suspiciousApps: spyApps,      // [스파이앱 탭으로]
                    privacyThreatApps: privacyThreats // [개인정보 유출 위협 탭으로]
                };
            },
    
    
            // iOS 데이터를 안드로이드 포맷으로 변환
            transformIosData(iosData) {
                console.log("📥 [Renderer] Main에서 받은 데이터:", iosData); // 디버깅용 로그
    
                // 1. 위협 데이터 매핑
                const suspiciousApps = (iosData.suspiciousItems || []).map(item => {
                    const moduleName = item.module || item.check_name || 'Unknown Module';
                    const description = item.description || item.name || '탐지된 이상 징후';
                    const filePath = item.file_path || item.path || '-';
    
                    return {
                        packageName: moduleName,
                        cachedTitle: `[iOS] ${moduleName}`,
                        reason: description,
                        apkPath: filePath,
                        hash: item.sha256 || 'N/A',
                        isSideloaded: true,
                        isRunningBg: false,
                        grantedList: [],
                        grantedCount: 0
                    };
                });
    
                // 2. 기기 정보 전달 (★ 핵심 수정 부분)
                // main.js에서 만든 deviceInfo가 있으면 무조건 그걸 씁니다.
                // 없으면(null이면) 그때서야 기본값을 씁니다.
                const finalDeviceInfo = iosData.deviceInfo || {
                    model: 'iPhone (Unknown)',
                    serial: '-',
                    isRooted: false,
                    phoneNumber: '-'
                };
    
                return {
                    deviceInfo: finalDeviceInfo, // ★ Main에서 준 정보를 그대로 통과시킴
                    allApps: iosData.allApps || [],
                    suspiciousApps: suspiciousApps,
                    apkFiles: []
                };
            },
    
            // 권한 한글 매핑
            getKoreanPermission(permString) {
                // 권한 한글 매핑 데이터 (Short Keys / Ultimate Edition)
                const MAP = {
                    'CAMERA': '📷 카메라',
                    'RECORD_AUDIO': '🎤 마이크 (녹음)',
                    'READ_CONTACTS': '📒 연락처 읽기',
                    'ACCESS_FINE_LOCATION': '📍 정밀 위치 (GPS)',
                    'READ_SMS': '✉️ 문자 읽기',
                    'SEND_SMS': '✉️ 문자 보내기',
                    'RECEIVE_BOOT_COMPLETED': '🔌 부팅 시 자동 실행',
                    'BIND_DEVICE_ADMIN': '🛡️ 기기 관리자 (삭제 방지)',
                    'INTERNET': '🌐 인터넷 사용',
                    'READ_EXTERNAL_STORAGE': '💾 저장소 읽기',
                    'WRITE_CONTACTS': '📒 연락처 쓰기/수정',
                    'CALL_PHONE': '📞 전화 걸기',
                    'READ_CALL_LOG': '📞 통화 기록 읽기',
                    'WRITE_CALL_LOG': '📞 통화 기록 쓰기/수정',
                    'PROCESS_OUTGOING_CALLS': '📞 발신 전화 가로채기/모니터링',
                    'ACCESS_COARSE_LOCATION': '📍 대략적 위치 (네트워크 기반)',
                    'SYSTEM_ALERT_WINDOW': '🪟 다른 앱 위에 화면 표시 (피싱/가로채기)',
                    'READ_PHONE_STATE': '📱 기기 정보/상태 읽기 (IMEI, 전화번호)',
                    'GET_ACCOUNTS': '🔑 계정 목록 접근 (Google, SNS 계정)',
                    'USE_BIOMETRIC': '🖐️ 지문/생체 인식 사용',
                    'REQUEST_INSTALL_PACKAGES': '📦 다른 앱 설치 요청',
                    'READ_CALENDAR': '🗓️ 캘린더 일정 읽기',
                    'WRITE_CALENDAR': '🗓️ 캘린더 일정 쓰기',
                    'WAKE_LOCK': '🔋 화면/CPU 잠금 방지',
                    'CHANGE_WIFI_STATE': '📶 Wi-Fi 연결 상태 변경',
                    'FOREGROUND_SERVICE': '🚀 포그라운드 서비스 실행 (백그라운드 지속)',
                    'ACCESS_WIFI_STATE': '📶 Wi-Fi 네트워크 상태 접근',
                    'READ_MEDIA_VISUAL_USER_SELECTED': '👀 미디어 (사진/영상) 선택적 접근',
                    'READ_MEDIA_IMAGES': '🖼️ 미디어 (사진) 전체 읽기',
                    'READ_MEDIA_VIDEO': '🎥 미디어 (영상) 전체 읽기',
                    'MANAGE_DOCUMENTS': '📁 문서 관리 (모든 파일 접근)',
                    'FOREGROUND_SERVICE_CAMERA': '📸 포그라운드 서비스: 카메라 사용',
                    'FOREGROUND_SERVICE_MICROPHONE': '🎙️ 포그라운드 서비스: 마이크 사용',
                    'FOREGROUND_SERVICE_MEDIA_PROJECTION': '📺 포그라운드 서비스: 화면 미디어 전송',
                    'FOREGROUND_SERVICE_DATA_SYNC': '🔄 포그라운드 서비스: 데이터 동기화',
                    'FOREGROUND_SERVICE_MEDIA_PLAYBACK': '🎵 포그라운드 서비스: 미디어 재생',
                    'RUN_USER_INITIATED_JOBS': '🔄 사용자 시작 작업 실행',
                    'NEARBY_WIFI_DEVICES': '📡 근처 Wi-Fi 기기 검색',
                    'ACCESS_NETWORK_STATE': '📶 네트워크 상태 확인',
                    'MODIFY_AUDIO_SETTINGS': '📢 오디오 설정 변경',
                    'NFC': '💳 NFC 사용 (근거리 무선 통신)',
                    'HIGH_SAMPLING_RATE_SENSORS': '📈 고주파수 센서 사용',
                    'USE_FINGERPRINT': '🖐️ 지문/생체 인식 사용',
                    'VIBRATE': '🔔 진동 제어',
                    'GET_PACKAGE_SIZE': '📦 앱 크기 정보 조회',
                    'DETECT_SCREEN_CAPTURE': '캡처/녹화 감지',
                    'POST_NOTIFICATIONS': '💬 알림 표시 요청',
                    'ACCESS_ADSERVICES_ATTRIBUTION': '📊 광고 기여도 서비스 접근',
                    'ACCESS_ADSERVICES_AD_ID': '🆔 광고 식별자 접근',
                    'USE_CREDENTIALS': '🔑 자격 증명 사용 (계정 인증 정보 활용)',
                    'MANAGE_ACCOUNTS': '🔑 계정 관리 (계정 추가, 삭제, 수정)',
                    'WRITE_SETTINGS': '⚙️ 시스템 설정 변경 (비행기 모드, 밝기 등)',
                    'BROADCAST_STICKY': '📢 지속적인 브로드캐스트',
                    'MEDIA_CONTENT_CONTROL': '⏯️ 미디어 제어',
                    'INTERACT_ACROSS_USERS': '👥 다른 사용자 상호작용',
                    'INTERACT_ACROSS_PROFILES': '👥 다른 프로필 상호작용',
                    'FOREGROUND_SERVICE_CONNECTED_DEVICE': '💻 포그라운드 서비스: 연결 기기 접근',
                    'WRITE_EXTERNAL_STORAGE': '💾 저장소 파일 쓰기/수정',
                    'ACCESS_NOTIFICATION_POLICY': '🔔 알림 정책 접근/변경',
                    'BLUETOOTH_ADMIN': '블루투스 설정 관리',
                    'CHANGE_NETWORK_STATE': '네트워크 연결 상태 변경',
                    'READ_PROFILE': '👤 사용자 프로필 정보 읽기',
                    'ACCESS_BACKGROUND_LOCATION': '📍 백그라운드 위치 접근 (백그라운드)',
                    'BLUETOOTH': '블루투스 연결/사용',
                    'CALL_PRIVILEGED': '📞 권한이 부여된 전화 걸기/수신',
                    'READ_ASSISTANT_APP_SEARCH_DATA': '🔍 어시스턴트 앱 검색 데이터 읽기',
                    'READ_SYNC_SETTINGS': '🔄 동기화 설정 읽기',
                    'GET_TASKS': '📋 최근 실행 앱 목록 조회',
                    'REAL_GET_TASKS': '📋 모든 실행 앱 목록 조회',
                    'WRITE_SMS': '✉️ 문자(SMS/MMS) 쓰기/수정',
                    'FLASHLIGHT': '💡 플래시 라이트 사용',
                    'DOWNLOAD_WITHOUT_NOTIFICATION': '📥 알림 없이 다운로드',
                    'MANAGE_VOICE_KEYPHRASES': '🗣️ 음성 키프레이즈 관리',
                    'MANAGE_SOUND_TRIGGER': '🔊 사운드 트리거 관리',
                    'SOUND_TRIGGER_RUN_IN_BATTERY_SAVER': '🔋 절전 모드에서 사운드 트리거 실행',
                    'CAPTURE_AUDIO_HOTWORD': '🎤 핫워드 오디오 캡처',
                    'MANAGE_HOTWORD_DETECTION': '🗣️ 핫워드 감지 관리',
                    'STOP_APP_SWITCHES': '앱 전환 차단',
                    'SET_WALLPAPER': '🖼️ 배경화면 설정',
                    'SET_WALLPAPER_HINTS': '🖼️ 배경화면 힌트 설정',
                    'BIND_APPWIDGET': '위젯 바인딩',
                    'CHANGE_WIFI_MULTICAST_STATE': '📶 Wi-Fi 멀티캐스트 상태 변경',
                    'SET_MEDIA_KEY_LISTENER': '⏯️ 미디어 키 리스너 설정',
                    'SET_VOLUME_KEY_LONG_PRESS_LISTENER': '🔊 볼륨 키 길게 누름 리스너 설정',
                    'MANAGE_USB': '🔌 USB 장치 관리',
                    'PACKAGE_USAGE_STATS': '📊 앱 사용 통계 접근',
                    'START_ACTIVITIES_FROM_BACKGROUND': '🚀 백그라운드에서 활동 시작',
                    'ANSWER_PHONE_CALLS': '📞 전화 받기/종료 자동 처리',
                    'EXPAND_STATUS_BAR': '상태 표시줄 확장',
                    'QUERY_ALL_PACKAGES': '📦 모든 설치된 앱 목록 조회',
                    'CONTROL_INCALL_EXPERIENCE': '📞 통화 중 경험 제어',
                    'ENTER_CAR_MODE_PRIORITIZED': '🚗 카 모드 우선권 진입',
                    'WRITE_APN_SETTINGS': '⚙️ APN 설정 쓰기',
                    'SCHEDULE_EXACT_ALARM': '⏰ 정확한 알람 예약',
                    'BLUETOOTH_CONNECT': '블루투스 연결',
                    'BLUETOOTH_SCAN': '블루투스 스캔',
                    'SUBSTITUTE_SHARE_TARGET_APP_NAME_AND_ICON': '🔗 공유 대상 이름/아이콘 대체',
                    'SUBSCRIBE_TO_KEYGUARD_LOCKED_STATE': '🔒 잠금 화면 상태 구독',
                    'EXECUTE_APP_ACTION': '▶️ 앱 동작 실행',
                    'EXECUTE_APP_FUNCTIONS': '▶️ 앱 기능 실행',
                    'CAPTURE_MEDIA_OUTPUT': '📺 미디어 출력 캡처',
                    'MODIFY_AUDIO_ROUTING': '📢 오디오 경로 변경',
                    'POST_PROMOTED_NOTIFICATIONS': '💬 홍보성 알림 표시',
                    'REORDER_TASKS': '📋 최근 실행 앱 순서 변경',
                    'CAPTURE_AUDIO_OUTPUT': '👂 오디오 출력 캡처 (스피커 소리)',
                    'SYSTEM_APPLICATION_OVERLAY': '🪟 시스템 앱 위에 오버레이 표시',
                    'AUTHENTICATE_ACCOUNTS': '🔑 계정 인증 자격 증명 사용',
                    'READ_SYNC_STATS': '🔄 동기화 통계 읽기',
                    'SUBSCRIBED_FEEDS_READ': '📰 구독 피드 읽기',
                    'SUBSCRIBED_FEEDS_WRITE': '📰 구독 피드 쓰기/수정',
                    'WRITE_SYNC_SETTINGS': '🔄 동기화 설정 쓰기/변경',
                    'REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': '🔋 배터리 최적화 무시 요청',
                    'REQUEST_PASSWORD_COMPLEXITY': '🔒 비밀번호 복잡도 설정 요청',
                    'MANAGE_OWN_CALLS': '📞 자체 통화 관리',
                    'USE_FULL_SCREEN_INTENT': '📱 전체 화면 인텐트 사용',
                    'FOREGROUND_SERVICE_PHONE_CALL': '📞 포그라운드 서비스: 전화 통화',
                    'ACCESS_KEYGUARD_SECURE_STORAGE': '🔒 키가드 보안 저장소 접근',
                    'WRITE_MEDIA_STORAGE': '💾 미디어 저장소 쓰기/수정',
                    'SET_PREFERRED_APPLICATIONS': '⚙️ 기본 앱 설정 변경',
                    'DEVICE_POWER': '🔋 기기 전원 상태 제어',
                    'GET_ACCOUNTS_PRIVILEGED': '🔑 특권 계정 목록 접근',
                    'WRITE_SECURE_SETTINGS': '⚙️ 보안 시스템 설정 쓰기',
                    'MANAGE_ROLE_HOLDERS': '👥 역할 소유자 관리',
                    'GET_INTENT_SENDER_INTENT': '의도 발신자 인텐트 획득',
                    'FINGERPRINT_PRIVILEGED': '🖐️ 지문 특권 사용',
                    'BIOMETRICS_PRIVILEGED': '🖐️ 생체 인식 특권 사용',
                    'READ_PRIVILEGED_PHONE_STATE': '📱 특권 기기 정보 읽기',
                    'CONFIGURE_WIFI_DISPLAY': '📺 Wi-Fi 디스플레이 설정',
                    'SEM_WRITE_CAPTURED_URL': '캡처된 URL 쓰기',
                    'FOREGROUND_SERVICE_SPECIAL_USE': '🚀 포그라운드 서비스: 특수 목적 사용',
                    'SSRM_NOTIFICATION_PERMISSION': '알림 권한 요청',
                    'STATUS_BAR': '상태 표시줄 제어',
                    'MANAGE_ACTIVITY_STACKS': '📋 활동 스택 관리',
                    'INSTALL_PACKAGES': '📦 패키지 설치',
                    'MODIFY_THEME': '테마 수정',
                    'FINGERPRINT_WEB_SIGNIN': '🖐️ 웹 로그인 지문 사용',
                    'IRIS_WEB_SIGNIN': '👁️ 웹 로그인 홍채 사용',
                    'INTELLIGENT_SCAN_WEB_SIGNIN': '스마트 스캔 웹 로그인',
                    'READ_MEDIA_AUDIO': '🎵 미디어 (오디오) 전체 읽기',
                    'READ_SEARCH_INDEXABLES': '🔍 검색 인덱스 가능 항목 읽기',
                    'BROADCAST_CLOSE_SYSTEM_DIALOGS': '시스템 대화상자 닫기 방송',
                    'MANAGE_USERS': '👥 사용자 계정 관리',
                    'CREDENTIAL_MANAGER_QUERY_CANDIDATE_CREDENTIALS': '🔑 자격 증명 후보 조회',
                    'CREDENTIAL_MANAGER_SET_ALLOWED_PROVIDERS': '🔑 허용된 자격 증명 제공자 설정',
                    'CREDENTIAL_MANAGER_SET_ORIGIN': '🔑 자격 증명 출처 설정',
                    'RECEIVE_SMS': '📩 문자 수신 감지 (몰래 수신)',
                    'RECEIVE_MMS': '📩 MMS(멀티미디어 문자) 수신',
                    'RECEIVE_WAP_PUSH': '📩 WAP 푸시 메시지 수신 (원격 명령)',
                    'BROADCAST_SMS': '📡 문자 메시지 방송 (시스템 권한)',
                    'READ_CELL_BROADCASTS': '📢 긴급 재난 문자/방송 읽기',
                    'READ_PHONE_NUMBERS': '📱 내 전화번호 가져오기',
                    'MODIFY_PHONE_STATE': '📱 전화 상태 조작 (통화 차단/가로채기)',
                    'USE_SIP': '📞 SIP(인터넷 전화) 사용',
                    'BIND_TELECOM_CONNECTION_SERVICE': '📞 통신 연결 서비스 바인딩',
                    'ACCEPT_HANDOVER': '📞 통화 전환 허용 (Wi-Fi ↔ LTE)',
                    'ACCESS_MEDIA_LOCATION': '🖼️ 사진 속 위치 정보(GeoTag) 읽기',
                    'ACCESS_LOCATION_EXTRA_COMMANDS': '📍 위치 제공자 추가 명령 실행',
                    'CONTROL_LOCATION_UPDATES': '📍 위치 업데이트 제어/조작',
                    'BIND_ACCESSIBILITY_SERVICE': '⚠️ [최고 위험] 접근성 서비스 (화면 제어/키로깅)',
                    'DELETE_PACKAGES': '🗑️ [시스템] 다른 앱 삭제',
                    'REPLACE_EXISTING_PACKAGE': '🔄 [시스템] 기존 앱 바꿔치기 (위변조)',
                    'CLEAR_APP_CACHE': '🧹 앱 캐시 삭제',
                    'CLEAR_APP_USER_DATA': '🧹 앱 사용자 데이터 초기화',
                    'MOVE_PACKAGE': '📦 앱 설치 위치 이동',
                    'INJECT_EVENTS': '⌨️ [해킹] 키 입력/터치 이벤트 주입 (원격 제어)',
                    'READ_INPUT_STATE': '⌨️ 키 입력 상태 읽기 (키로깅)',
                    'READ_LOGS': '📝 [시스템] 시스템 로그 읽기 (민감 정보 유출)',
                    'DUMP': '📝 [시스템] 시스템 상태 정보 덤프',
                    'SET_ACTIVITY_WATCHER': '👀 앱 실행 감시자 설정',
                    'SET_PROCESS_LIMIT': '🛑 백그라운드 프로세스 제한',
                    'SIGNAL_PERSISTENT_PROCESSES': '🛑 지속 프로세스 종료 신호',
                    'KILL_BACKGROUND_PROCESSES': '🔪 다른 앱 강제 종료',
                    'FORCE_STOP_PACKAGES': '🔪 앱 강제 중지',
                    'REBOOT': '🔄 기기 재부팅',
                    'SHUTDOWN': '📴 기기 전원 끄기',
                    'FACTORY_TEST': '🏭 공장 초기화 테스트 모드 진입',
                    'MASTER_CLEAR': '💥 [매우 위험] 공장 초기화 (데이터 전체 삭제)',
                    'BRICK': '🧱 기기 벽돌화 (영구 손상 시도)',
                    'DISABLE_KEYGUARD': '🔓 잠금 화면(패턴/비번) 해제',
                    'BATTERY_STATS': '🔋 배터리 사용량 통계 조회',
                    'WRITE_GSERVICES': '⚙️ 구글 서비스 설정 변경',
                    'CHANGE_CONFIGURATION': '⚙️ UI 구성 변경 (언어/방향)',
                    'CHANGE_COMPONENT_ENABLED_STATE': '🚫 앱 아이콘 숨기기/비활성화',
                    'PERSISTENT_ACTIVITY': '🧟 앱이 메모리에서 죽지 않도록 설정',
                    'RESTART_PACKAGES': '🔄 앱 재시작',
                    'MANAGE_EXTERNAL_STORAGE': '⚠️ [위험] 모든 파일 관리 접근',
                    'ACCESS_MTP': '🔌 MTP 프로토콜 접근',
                    'MOUNT_UNMOUNT_FILESYSTEMS': '💾 SD카드 마운트/해제',
                    'MOUNT_FORMAT_FILESYSTEMS': '💾 저장소 포맷/초기화',
                    'FOREGROUND_SERVICE_LOCATION': '📍 포그라운드: 위치 추적',
                    'FOREGROUND_SERVICE_HEALTH': '❤️ 포그라운드: 건강 데이터',
                    'FOREGROUND_SERVICE_REMOTE_MESSAGING': '📨 포그라운드: 원격 메시징',
                    'INSTANT_APP_FOREGROUND_SERVICE': '⚡ 인스턴트 앱 포그라운드 실행',
                    'CONNECTIVITY_INTERNAL': '📶 [시스템] 내부 네트워크 관리',
                    'CONTROL_VPN': '🔒 VPN 연결 제어',
                    'TETHER_PRIVILEGED': '📡 핫스팟/테더링 제어',
                    'BLUETOOTH_ADVERTISE': '🦷 블루투스 신호 송출',
                    'BLUETOOTH_PRIVILEGED': '🦷 [시스템] 블루투스 특권',
                    'NFC_TRANSACTION_EVENT': '💳 NFC 결제 이벤트 수신',
                    'UWB_RANGING': '📏 UWB(초광대역) 거리 측정',
                    'BIND_NOTIFICATION_LISTENER_SERVICE': '📩 [위험] 알림 내용 훔쳐보기 (카톡/문자)',
                    'COLLAPSE_STATUS_BAR': '⬆️ 상태 표시줄 축소',
                    'ACCESS_SURFACE_FLINGER': '🖥️ 화면 프레임 버퍼 접근 (스크린샷)',
                    'READ_FRAME_BUFFER': '🖥️ 화면 내용 읽기 (스크린샷)',
                    'INTERNAL_SYSTEM_WINDOW': '🪟 내부 시스템 윈도우 사용',
                    'USE_IRIS': '👁️ 홍채 인식 사용',
                    'USE_FACE_AUTHENTICATION': '🙂 얼굴 인식 사용',
                    'BODY_SENSORS': '❤️ 신체 센서(심박수 등) 접근',
                    'BODY_SENSORS_BACKGROUND': '❤️ 백그라운드 신체 센서 접근',
                    'ACTIVITY_RECOGNITION': '🏃‍♂️ 활동 감지',
                    'HARDWARE_TEST': '🛠️ 하드웨어 테스트',
                    'TRANSMIT_IR': '📡 적외선(IR) 송신',
                    'CAMERA_DISABLE_TRANSMIT_LED': '📷 카메라 촬영 중 LED 끄기 (몰카)',
                    'ACCOUNT_MANAGER': '👤 계정 매니저 접근',
                    'BIND_INPUT_METHOD': '⌨️ 키보드(IME) 앱 바인딩',
                    'BIND_VPN_SERVICE': '🔒 VPN 서비스 바인딩',
                    'BIND_WALLPAPER': '🖼️ 배경화면 서비스 바인딩',
                    'BIND_VOICE_INTERACTION': '🗣️ 음성 인식 서비스 바인딩',
                    'BIND_REMOTE_VIEWS': '📱 원격 뷰 바인딩',
                    'BIND_TEXT_SERVICE': '📝 텍스트 서비스 바인딩',
                    'BIND_DREAM_SERVICE': '💤 화면보호기 바인딩',
                    'BIND_CARRIER_MESSAGING_SERVICE': '📨 통신사 메시징 서비스 바인딩',
                    'INSTALL_SHORTCUT': '📌 홈 화면 바로가기 추가',
                    'UNINSTALL_SHORTCUT': '📌 홈 화면 바로가기 삭제',
                    'SET_TIME_ZONE': '⏰ 시간대 변경',
                    'SET_TIME': '⏰ 시스템 시간 변경',
                    'READ_HISTORY_BOOKMARKS': '🌐 브라우저 기록 읽기',
                    'WRITE_HISTORY_BOOKMARKS': '🌐 브라우저 기록 조작',
                    'SET_ALARM': '⏰ 알람 설정',
                    'KNOX_SECURITY': '🛡️ 삼성 Knox 보안 제어',
                    'KNOX_DEVICE_ADMIN': '🛡️ 삼성 Knox 관리자',
                    'KNOX_CUSTOM_SYSTEM': '🛡️ 삼성 Knox 커스텀 시스템',
                    'KNOX_HW_CONTROL': '🛡️ 삼성 Knox 하드웨어 제어',
                    'KNOX_APP_MGMT': '🛡️ 삼성 Knox 앱 관리',
                    'KNOX_RESTRICTION_MGMT': '🛡️ 삼성 Knox 제한 관리',
                    'SAMSUNG_PAY': '💳 삼성페이 접근',
                    'DVFS_BOOSTER_PERMISSION': '🚀 삼성 성능 부스터 제어',
                    'WRITE_USE_APP_FEATURE_SURVEY': '📝 삼성 사용 패턴 수집',
                    'COCKTAIL_BAR_SERVICE': '🍸 삼성 엣지 패널 제어',
                    'ACCESS_PROVIDER': '📧 삼성 이메일 접근',
                    'ADD_ACCOUNT': '👤 삼성 계정 추가',
                    'USE_FACE': '🙂 삼성 얼굴 인식',
                    'IMAGE_ENHANCE': '📷 삼성 카메라 화질 개선',
                    'LAUNCH_PERSONAL_PAGE_SERVICE': '🔐 삼성 프라이빗 모드 실행',
                    'BILLING': '💰 구글 플레이 결제',
                    'CHECK_LICENSE': '©️ 라이선스 확인',
                    'RECEIVE': '☁️ 푸시 알림 수신 (Google/Firebase)',
                    'READ_GSERVICES': '🔧 구글 서비스 설정 읽기',
                    'BIND_GET_INSTALL_REFERRER_SERVICE': '📢 앱 유입 경로 추적',
                    'GOOGLE_PHOTOS': '🖼️ 구글 포토 접근',
                    'READ_GMAIL': '📧 지메일(Gmail) 읽기',
                    'WRITE_GMAIL': '📧 지메일(Gmail) 쓰기',
                    'LGE_CAMERA_VERIFY': '📷 LG 카메라 검증',
                    'READ_SETTINGS': '⚙️ 런처 설정 읽기 (제조사 공통)',
                    'BROADCAST_BADGE': '🔴 앱 배지 제어 (Sony/HTC)',
                    'PROVIDER_INSERT_BADGE': '🔴 배지 삽입',
                    'UPDATE_SHORTCUT': '📌 바로가기 업데이트',
                    'CHANGE_BADGE': '🔴 화웨이 앱 배지 변경',
                    'MDM': '🛡️ MDM(모바일 기기 관리) 보안 제어',
                    'EXTRA_NETWORK': '📶 샤오미 네트워크 추가 권한',
                    'PERM_USE_ANALYTICS': '📊 샤오미 분석 데이터 사용',
                    'USE_EXACT_ALARM': '⏰ 정확한 알람 사용 (시스템 승인 필요 없음)',
                    'SCHEDULE_EXACT_ALARM': '⏰ 정확한 알람 예약 (사용자 권한 필요)',
                    'ACCESS_MEDIA_LOCATION': '📍 미디어 파일 위치 정보(GeoTag) 읽기',
                    'READ_MEDIA_VISUAL_USER_SELECTED': '👀 사용자가 직접 선택한 사진/영상만 접근',
                    'POST_NOTIFICATIONS': '🔔 앱 알림 보내기 (Android 13+)',
                    'REVOKE_POST_NOTIFICATIONS_WITHOUT_KILL': '🔕 앱 종료 없이 알림 권한 회수',
                    'NEARBY_WIFI_DEVICES': '📡 근처 Wi-Fi 기기 탐색 (위치 정보 없이)',
                    'UWB_RANGING': '📏 UWB(초광대역) 정밀 거리 측정',
                    'MANAGE_MEDIA_PROJECTION': '📺 화면 공유/캡처 세션 관리',
                    'REQUEST_DELETE_PACKAGES': '🗑️ 앱 삭제 요청 (사용자 확인)',
                    'UPDATE_PACKAGES_WITHOUT_USER_ACTION': '🔄 사용자 개입 없이 앱 업데이트',
                    'ADD_VOICEMAIL': '📼 음성 사서함 메시지 추가',
                    'READ_VOICEMAIL': '📼 음성 사서함 읽기',
                    'WRITE_VOICEMAIL': '📼 음성 사서함 쓰기/삭제',
                    'READ_PRECISE_PHONE_STATE': '📱 정밀한 통화 상태 읽기 (데이터 연결 등)',
                    'BIND_VISUAL_VOICEMAIL_SERVICE': '📼 비주얼 보이스메일 서비스 바인딩',
                    'BIND_CARRIER_SERVICES': '📡 통신사 전용 서비스 바인딩',
                    'BIND_CALL_REDIRECTION_SERVICE': '↪️ 발신 전화 리디렉션 서비스 바인딩',
                    'BIND_SCREENING_SERVICE': '📞 스팸 전화 스크리닝 서비스 바인딩',
                    'READ_USER_DICTIONARY': '📖 사용자 단어장/사전 읽기',
                    'WRITE_USER_DICTIONARY': '📖 사용자 단어장/사전 쓰기',
                    'SET_ORIENTATION': '🔄 화면 회전 방향 강제 설정',
                    'SET_POINTER_SPEED': '🖱️ 마우스/터치패드 포인터 속도 설정',
                    'BIND_QUICK_SETTINGS_TILE': '🔘 퀵 설정(상단바) 타일 추가/관리',
                    'BIND_INPUT_METHOD': '⌨️ 키보드(IME) 입력기 바인딩',
                    'BIND_MIDI_DEVICE_SERVICE': '🎹 MIDI 악기 연결 서비스 바인딩',
                    'MANAGE_WIFI_INTERFACES': '📶 Wi-Fi 인터페이스 직접 제어',
                    'OVERRIDE_WIFI_CONFIG': '📶 Wi-Fi 설정 강제 덮어쓰기',
                    'GLOBAL_SEARCH': '🔍 전역 검색 데이터 접근',
                    'SET_ALWAYS_FINISH': '🛑 액티비티 유지 안 함 (개발자 옵션)',
                    'SET_ANIMATION_SCALE': '🎞️ 애니메이션 배율 설정 (개발자 옵션)',
                    'SET_DEBUG_APP': '🐞 디버깅 앱 설정',
                    'CAR_SPEED': '🚗 차량 속도 정보 읽기',
                    'CAR_MILEAGE': '🚗 차량 주행 거리 정보 읽기',
                    'CAR_FUEL': '⛽ 차량 연료량 확인',
                    'CAR_VENDOR_EXTENSION': '🚗 차량 제조사 확장 기능 사용',
                    'CONTROL_CAR_CLIMATE': '❄️ 차량 에어컨/히터 제어',
                    'CONTROL_CAR_DOORS': '🚪 차량 문 잠금/해제',
                    'CONTROL_CAR_WINDOWS': '🪟 차량 창문 제어',
                    'BIND_COMPANION_DEVICE_SERVICE': '⌚ 웨어러블/컴패니언 기기 연결 관리',
                    'REQUEST_COMPANION_RUN_IN_BACKGROUND': '⌚ 컴패니언 기기 백그라운드 실행 유지',
                    'REQUEST_COMPANION_USE_DATA_IN_BACKGROUND': '⌚ 컴패니언 기기 백그라운드 데이터 사용',
                    'ACCESS_VR_STATE': '🥽 VR(가상현실) 모드 상태 접근',
                    'ACCESS_AMBIENT_LIGHT_STATS': '💡 주변 밝기 센서 통계 접근',
                    'BODY_SENSORS_BACKGROUND': '❤️ 백그라운드에서 신체 센서(심박 등) 접근',
                    'USE_ICC_AUTH_WITH_DEVICE_IDENTIFIER': '🔑 기기 식별자를 이용한 ICC 인증',
                    'MANAGE_FINGERPRINT': '🖐️ 지문 데이터 관리 (등록/삭제)',
                    'RESET_FINGERPRINT_LOCKOUT': '🔓 지문 인식 실패 잠금 초기화',
                    'MANAGE_BIOMETRIC': '👤 생체 인식 데이터 관리',
                    'COPY_PROTECTED_DATA': '©️ 보호된 데이터 복사 (시스템)',
                    'FORCE_BACK': '🔙 뒤로 가기 강제 실행',
                    'MANAGE_APP_OPS_MODES': '🛡️ 앱 권한(AppOps) 강제 조작',
                    'UPDATE_DEVICE_STATS': '📊 기기 통계 강제 업데이트',
                    'CHANGE_APP_IDLE_STATE': '💤 앱 절전(Doze) 모드 상태 변경',
                    'MANAGE_NOTIFICATIONS': '🔔 모든 알림 관리/삭제 (시스템)',
                    'RETRIEVE_WINDOW_CONTENT': '🪟 화면 창 내용 추출 (접근성)',
                    'TABLET_MODE': '📱 태블릿 모드 전환',
                    'STATUS_BAR_SERVICE': '⬇️ 상태 표시줄 서비스 바인딩'
                };
                const shortName = permString.split('.').pop();
                return MAP[shortName] || shortName;
            }
        };
